name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Biome checks
        run: bun run check

      - name: Run markdownlint
        run: bun run lint:md

      - name: Run type checking
        run: bun run typecheck

      - name: Run tests
        run: bun test

